# Generated by Django 5.0 on 2023-12-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre_producto", models.CharField(max_length=100)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("descripcion", models.CharField(max_length=150, null=True)),
                ("img_producto", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
